### ISSUE TITLE
upgrade isemail to lab 8.x

### ISSUE THREAD

**Issue by lloydbenson** [hapijs/isemail#16]
I tried this and there was only one issue which was an err was unhandled.  I wasn't sure how you wanted to handle it so I just opened an issue without a PR for this one.

**Comment by skeggse** [comment]
There is no good solution to this issue. If I recall correctly, I used to have an additional check on [line 1338](https://github.com/hapijs/isemail/blob/6e24ff61e4be4a8157413d41737272f5531756d8/lib/index.js#L1338) (`if (!err && records && records.length) {` instead of `if (records && records.length) {`). Including the `!err` resulted in incomplete code coverage, and switching to `if (!err && records.length) {` is the wrong direction - I don't care if there's an error, just whether there were any records located, and my code should reflect that. Thoughts?

**Comment by hueniverse** [comment]
If ignoring the error is save, rename `err` to `ignoreError`

**Comment by skeggse** [comment]
Perfect, thanks!
