### ISSUE TITLE
minDomainAtoms and tld

### ISSUE THREAD

**Issue by Sorrow** [hapijs/isemail#182]
Hi,
i may misunderstand the minDomainAtoms property, but why those emails are considered valid ?

`Isemail.validate('shouldbe@invalid.c', {
            errorLevel: 0,
            minDomainAtoms: 2
        })`

`Isemail.validate('shouldbe@invalid.com', {
            errorLevel: 0,
            minDomainAtoms: 4
        })`

Thanks.

**Comment by skeggse** [comment]
`shouldbe@invalid.c` is considered valid with `minDomainAtoms=2` because it has two domain atoms. The first atom is `invalid`, and the second atom is `c`.

`shouldbe@invalid.com` is not considered valid with `minDomainAtoms=4` because it has two domain atoms. I'm not sure what you're seeing that makes you think it's considered valid.

**Comment by Sorrow** [comment]
Thanks for your answer, i have been misled by some minDomainAtoms usage i have seen around and couldn't figure out how i should have intrepreted this property from the test suite.

**Comment by Sorrow** [comment]
@skeggse Yeah thanks, that clears out everything :)
